name: Compile Course Notes

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/[0-9A-Z]_*.tex'

permissions:
  contents: write

jobs:
  build:
    uses: RiccardoElena/UniNotes_Template/.github/workflows/latex-compile-ci.yaml@master
    with:
      pdf_name: 'Logic_for_Computer_Science'
